### ISSUE TITLE
Firefox cannot render Tossface Webfont

### ISSUE THREAD

**Issue by anaclumos** [toss/tossface#21]
When embedding on a website as a JsDelivr embed, Tossface font doesn't render on Firefox. It correctly renders on Chrome and Safari though.

- Minimum Reproduction: https://github.com/anaclumos/tossface-firefox-bug-report/
- Playwright Report: [https://tossface-firefox-bug-report.vercel.app/playwright-report/index.html](https://tossface-firefox-bug-report.vercel.app/playwright-report/index.html)

**Comment by anaclumos** [comment]
![image](https://github.com/user-attachments/assets/2ed163b9-14f5-4123-bd6b-dc69efefc587)

**Comment by anaclumos** [comment]
@sudosubin Are there any updates to this matter?

**Comment by kms0219kms** [comment]
@anaclumos As far as I know, @sudosubin is no longer works for @toss.
That's why this repo seems no longer maintained. I hope other developers at Toss will look into this.

**Comment by kms0219kms** [comment]
@anaclumos And, if you mind, please test with this page: https://toss.im/tossface.
If the emojis on that page works, you can temporarily use this code:
```css
/* Extracted from view-source:https://toss.im/tossface */
@font-face {
   font-family:'TossFaceFontWeb';
   src: url('https://static.toss.im/tossface-font/TossFaceFontWeb.otf') format('truetype');
   font-weight: 500;
}
```
